# Based off the RHAII 3.4.1 image.
FROM registry.redhat.io/rhaii/vllm-cuda-rhel9@sha256:5800e12b2a465f15961fcf34b645d79ed4f91ec9161eab22b1205d12682183c8

RUN pip install --no-cache-dir --extra-index-url https://pypi.org/simple/ instanttensor
