## Original InferenceService object, without any compilation caching put into it.

apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: qwen35-4b
spec:
  predictor:
    automountServiceAccountToken: false
    deploymentStrategy:
      type: RollingUpdate
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: vLLM
      name: ''
      resources:
        limits:
          cpu: '2'
          memory: 8Gi
          nvidia.com/gpu: '1'
        requests:
          cpu: '2'
          memory: 8Gi
          nvidia.com/gpu: '1'
      runtime: qwen35-4b
      storageUri: 'hf://Qwen/Qwen3.5-4b'
    timeout: 30
